name: example-environment
channels: 
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - traitlets
  - ipywidgets
  - bqplot
  - DropDown
  - VBox
  - HBox
  - Layout
  - HoverTool
  - output_notebook
  - show
  - bokeh
  - bokeh.io
  - bokeh.plotting
  - bokeh.models
